import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import SideUserBar from '@/components/SideUserBar'
import MainContent from '@/components/MainContent'
import OtherSideBar from '@/components/OtherSideBar'
import dynamic from 'next/dynamic'
import { GetServerSidePropsContext } from 'next';
import {useEffect} from "react"
import axios from "axios";

const inter = Inter({ subsets: ['latin'] })

const Home: React.FC<{props: any}> = ({props}) => {
    useEffect(() => {
        const fetchData = async () => {
            const results = await axios.get("https://8f7b-196-47-228-190.ngrok-free.app/api/account");
            console.log(results)
        }
        // fetchData();
    }, [])
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SideUserBar />
        <MainContent />
        <OtherSideBar />
      </main>
    </>
  )
}

export default dynamic (() => Promise.resolve(Home), {ssr: false})
