import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Register.module.css';
import {BiText, BiMessageDetail} from "react-icons/bi";
import {RxDividerVertical} from "react-icons/rx";
import {AiOutlineMail} from "react-icons/ai";
import {MdPassword} from "react-icons/md";
import { UserDetails } from '@/types/types';
import useRandom from '@/hooks/useRandom';
import {FormEvent, useState} from "react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const randomId = useRandom();
  const [userDetails, setUserDetails] = useState<UserDetails>({
      accountId: randomId,
      name: "",
      email: "",
      password: "",
      description: "",
      followers: 0,
      posts: []
  });

  const submit = async (e: FormEvent) => {
    e.preventDefault();
    const results = await fetch(" https://8f7b-196-47-228-190.ngrok-free.app/api/account/add", {
      method: "POST",
      body: JSON.stringify(userDetails)
    });
    const response = results.json();
    console.log(response);
  }

  return (
    <>
      <Head>
        <title>Create</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <form className={styles.mainForm} onSubmit={submit} method='POST'>
            <h1 className={styles.mainFormTitle}>Create Account</h1>
            <section className={styles.mainFormInputs}>
              <div className={styles.mainFormInputsEach}>
                <input 
                  className={styles.mainFormInputsEachInput} 
                  type="text" 
                  placeholder='Enter your fullname...' 
                  value={userDetails.name}
                  onChange={(e) => setUserDetails({...userDetails, name: e.target.value})}
                  required />
                <RxDividerVertical className={styles.mainFormInputsEachLine} />
                <BiText className={styles.mainFormInputsEachIcon} />
              </div>
              <div className={styles.mainFormInputsEach}>
                <input 
                  className={styles.mainFormInputsEachInput} 
                  type="email" 
                  value={userDetails.email}
                  placeholder='Enter your email...' 
                  onChange={(e) => setUserDetails({...userDetails, email: e.target.value})}
                  required />
                <RxDividerVertical className={styles.mainFormInputsEachLine} />
                <AiOutlineMail className={styles.mainFormInputsEachIcon} />
              </div>
              <div className={styles.mainFormInputsEach}>
                <textarea 
                  placeholder='Enter your description...' 
                  value={userDetails.description}
                  onChange={(e) => setUserDetails({...userDetails, description: e.target.value})}
                  required 
                  className={styles.mainFormInputsEachText} />
                <RxDividerVertical className={styles.mainFormInputsEachLine} />
                <BiMessageDetail className={styles.mainFormInputsEachIcon} />
              </div>
              <div className={styles.mainFormInputsEach}>
                <input 
                  className={styles.mainFormInputsEachInput} 
                  type="password" 
                  placeholder='Enter your password...' 
                  value={userDetails.password}
                  onChange={(e) => setUserDetails({...userDetails, password: e.target.value})}
                  required />
                <RxDividerVertical className={styles.mainFormInputsEachLine} />
                <MdPassword className={styles.mainFormInputsEachIcon} />
              </div>
            </section>
            <button className={styles.mainFormButton} type='submit' onSubmit={submit}>Create account</button>
          </form>
      </main>
    </>
  )
}
